sim0n00ps/OF-DL

OF DL/Entities/Auth.cs
OF DL/Helpers/APIHelper.cs

Particularly useful for free accounts where some creators post a lot of other user's content as an ad. These posts are usually time-limited, but if you download all of the posts from that user, you pick up the ad content.
I had a bit of trouble working out where to most effectively add this, but this seemed like the most effective spot. Likewise, I've tries to test it as much as I can, but I couldn't reproduce exactly the build you use for releases, so I've just tested what I could.

Add option to skip posts with ads/trials;

---

OF DL/Entities/Config.cs
OF DL/Helpers/APIHelper.cs

Maybe it's compounded by my slow Internet but I noticed that it was possible for the API calls (especially to `/users/<user-id>/posts`) to timeout before completing with the default timeout of 100 seconds. Rather than just cranking that up to something higher, I thought it might be good to make it configurable, so I've added a helper to create the `HttpClient` with either the default timeout or a timeout from the `config.json`.
By default, this will just use the default timeout, but setting it in the config file should now be used in most of the API calls (at least the ones where `Config` was available). Feels like a sufficiently niche case that it probably doesn't warrant adding to the config menu, but I'll leave that call up to you.

Make HTTP timeout for API calls configurable;

---

OF DL/Program.cs

Did not test on Windows, but should work fine as it is now platform agnositc. The current, ad-hoc, regex based validator fails on Linux (and probably other) filepaths. 
(As an aside, it would be nice if this project removed spaces from the folder and file names, since they're annoying on Linux. E.g. "OF DL.dll" -> "OF_DL.dll".)

Fix file path validation for non-Windows OSs

---

OF DL/Helpers/APIHelper.cs
OF DL/Helpers/DownloadHelper.cs
OF DL/Helpers/FileNameHelper.cs
OF DL/Utils.cs

Add post rawText to the database instead of text. Filter out invalid file name characters to prevent filename errors. These changes allow the {rawText} tag to be used for PostFileNameFormat and PaidPostFileNameFormat. {text} tag can be used for the others (as well as the previously mentioned ones) though html content may be present in the output.

Use rawText and Prevent Errors

---

OF DL/Entities/Config.cs
OF DL/Helpers/APIHelper.cs
OF DL/Helpers/DBHelper.cs
OF DL/Helpers/Interfaces/IDBHelper.cs

Just a quick implementation of a "incremental post download" to speed up creator downloads to see if there's any bites for it.
The idea is to avoid excessive calls to the API just to get Posts data for items that have already been downloaded, since we don't care. 
It checks the SQLite DB for the latest post downloaded or the first post that hasn't downloaded, and uses that DateTime to to query the API for available posts from.
If the CustomDate functionality is enabled, then incremental downloads are disabled. This functionality is most also be enabled in the config file.

feat: add support to download posts incrementally

---

Dockerfile
OF DL/Helpers/DownloadHelper.cs
docker/entrypoint.sh

This PR contains a Dockerfile and entrypoint script to allow users to run OF-DL in a docker container. This will allow users to run OF-DL on operating systems other than Windows without having to setup a .NET development environment.
To build an OF-DL docker image, simply execute:
`docker build -t of-dl .` in the root of the repository
To run OF-DL in a docker container, then execute:
`docker run -it -v /{path to data directory}/:/data /{path to config directory}/:/config of-dl`
`{path to data directory}` should be replaced with the path to the folder on your computer where the downloaded data should be saved. `{path to config directory}` should be replaced with the path to the folder on your computer where you want to store the config for OF-DL. If `auth.json` and `config.json` don't …

Add docker configuration

---

OF DL/Entities/Config.cs
OF DL/Program.cs
docker/entrypoint.sh

This PR adds the ability (by setting `NonInteractiveMode` to `true` in the config) for OF-DL to be run without requiring user interaction. In combination with the docker configuration, this will allow systems to automatically run OF-DL on a schedule. For instance, I run an OF-DL docker container on my unraid server. I have a scheduler start the container daily to automatically download content.
Future improvements could include adding optional notification options. For instance, a notification could be sent to configured notifiers when auth fails, DRM decryption fails, etc. I personally like the way [charlocharlie/epicgames-freegames](https://hub.docker.com/r/charlocharlie/epicgames-freegames) handles notifications. That project could be used as a template for setting up notifiers

Add non-interactive mode

---

OF DL/Helpers/DownloadHelper.cs
OF DL/Program.cs

This PR includes a cross platform fix for the FFmpeg process deadlock. According to the docs, a deadlock can occur when redirecting standard error or standard output if it is not read (before calling WaitForExit).
The backslash escaping code just improves on your hotfix to only affect windows and to also fix an unescaped (if possible) path set by the user in config.

Fix unescaped backslashes and drm download deadlock

---

OF DL/Entities/DynamicRules.cs
OF DL/Helpers/APIHelper.cs
OF DL/Helpers/Constants.cs

This PR changes the source of the OnlyFans dynamic rules from [deviint/onlyfans-dynamic-rules](https://github.com/deviint/onlyfans-dynamic-rules) to [SneakyOvis/onlyfans-dynamic-rules](https://github.com/SneakyOvis/onlyfans-dynamic-rules).
The new source uses GitHub Actions to automatically update the dynamic rules every 15 minutes if there are any changes. As a bonus, the source code is publicly available which isn't the case with the current source.

Change dynamic rules source

---

.github/workflows/publish.yml

This PR adds a GitHub Actions workflow to automatically publish docker images to GitHub Container Registry (ghcr) when a new release tag is pushed. Whenever a tag is pushed with the `OFDLV` prefix, a docker image is built and pushed to both the latest tag and the version tag. For example, if the `OFDLV1.9.3` tag is pushed, `ghcr.io/sim0n00ps/of-dl:latest` and `ghcr.io/sim0n00ps/of-dl:1.9.3` will be pushed to ghcr.
Unless you've changed the repository's GitHub Actions settings to non-default values, only one setting will need to be updated to support this PR. On the [Actions (General) page](https://github.com/sim0n00ps/OF-DL/settings/actions), under `Workflow permissions`, be sure that `Read and write permissions` is selected. This will ensure that the GITHUB_TOKEN used by the workflow has …

Use GitHub actions to publish docker images

---

OF DL/Program.cs

* Update various `Environment.Exit()` calls to use non-zero exit codes to properly indicate a failure.
* In the primary `catch {}` block of the `Main()` function, wait for user keypress before exiting, so users have a chance to see the error if they are not running it underneath an existing console window.

More error handling

---

.gitignore
OF DL/CDMApi.cs
OF DL/Entities/Config.cs
OF DL/Entities/IDownloadConfig.cs
OF DL/Helpers/APIHelper.cs
OF DL/OF DL.csproj
OF DL/Program.cs
OF DL/Widevine/CDM.cs
OF DL/Widevine/Constants.cs

Add an option to bypass downloading purchased content for creators who no longer exist. Useful if you already have their content, and dont want to redownload it all as "deleted user - {ID}".
Also added a small improvement to handle users who no longer exist.
It was very difficult to test this properly, as I had to manipulate data in-memory at the right points...

Add option to bypass missing creator content

---

OF DL/Program.cs

Also trim some trailing whitespaces.

Move Environment.Exit() calls outside of the non-interactive conditional block.

---

OF DL/Helpers/DownloadHelper.cs

Fixes #421. Upon investigation, it was indeed an oversight.
By the way, in this `DownloadAvatarHeader` method, the codes for the avatar and for the header are nearly identical. There is some potential for code factorization here.

Fix erroneous filename of downloaded profile header

---

.github/workflows/publish.yml

Macs using Apple Silicon are on an ARM chip rather than a x64 chip. This addiction pushes both `amd64` and `arm64` Docker images when a new release is created, so the instructions on how to use them remain the same, it'll just work correctly for those users.

Add arm64 support for Docker

---

OF DL/Helpers/DownloadHelper.cs

I had a stray file, and it got all the way to FFMpeg to download the media, but the program got stuck.
FFMpeg was waiting for a input response to overwrite an existing file. 
This just adds the `-y` command line parameter to signal the yes.

fix: ffmpeg always overwrite existing if it exists

---

.github/workflows/publish.yml
Dockerfile
OF DL/OF DL.csproj
OF DL/Program.cs

I've noticed in discord that users frequently confused about their program version. Also, users frequently post screenshots of their console output. By printing the program version on start-up, a lot of common back-and-forth in discord can be eliminated.
A downside of this functionality, though, ~~is that you will need to manually update the version in `OF DL/OF DL.csproj` before each release.~~ is that you'll need to use an additional build argument when building releases (e.g. `-p Version=1.7.61`). I personally think the trade-off is worth it, but I won't be the one updating the version each time :laughing: 
In the future, a config option can be added to automatically check for updates. A github API request could be made to compare the current program version to the most recent release …

Print program version on start-up

---

OF DL/Entities/Config.cs
OF DL/Entities/IDownloadConfig.cs
OF DL/Enumerations/LoggingLevel.cs
OF DL/Helpers/APIHelper.cs
OF DL/OF DL.csproj
OF DL/Program.cs

- Removed the "enable debug" option from config
- We now have 5 different logging levels which can be set
- Logging enabled by default, but set to Error (so nothing only exceptions are logged)
- The next PR will be me adding different more logging statements, but with the relevant logging level

Added ability to change log level - default level set to Error

---

Dockerfile

Changed over to use alpine since it supports dotnet8 and ffmepg without adding a ppa.
Tested it with both docker and podman, builds without an issue.

feat: change Dockerfile to use alpine

---

Dockerfile
docker/entrypoint.sh

This PR makes 3 changes
- Automatically generate default `auth.json` and `config.json` files similar to the windows build process instead of using the previously hard-coded values
- Specify the alpine version (should help to maintain consistent builds in the future when alpine has a new version)
- Add the [tini init system](https://github.com/krallin/tini) as a best practice for containers

Docker improvements

---

OF DL/Entities/Archived/Archived.cs
OF DL/Entities/Post/Post.cs
OF DL/Entities/Post/SinglePost.cs
OF DL/Entities/Streams/Streams.cs
OF DL/Utils/XmlUtils.cs

The API isn't returning `rawText` on some posts, so adding logic to parse it locally from the returned `text` value.

fix: parse rawTax from text is missing

---

OF DL/Entities/Config.cs

I noticed while updating the docs that our default value for `ShowScrapeSize` is true. Prior to the automatic `config.json` (v1.7.61 and before), the default was false. We have warning about this in the docs, but due to the performance hit and potential rate limiting of this config option, I think the default should be false.

Change default value of ShowScrapeSize to false

---

docs/docs/installation/docker.md

A recent message in discord mentioned that the user was accumulating stopped OF-DL containers. This change updates the recommended `docker run` command to include a `--rm` flag to automatically delete the container when it stops.

Add --rm to docker run command

---

OF DL/Helpers/APIHelper.cs

I noticed when looking through my debug log recently that OF-DL is making a lot of unnecessary network calls to retrieve the dynamic rules. This PR caches the dynamic rules from GitHub for 15 minutes and from local file for 5 minutes. Since the dynamic rules don't change often, the 15 minute cache should be just fine. The 5 minute cache when the dynamic rules are retrieved from the local file exists to limit the number of bad/failing requests to GitHub (which would be the cause for using the local file).

Cache the dynamic rules response 

---

docker/entrypoint.sh
docker/supervisord.conf

The cause of the browser login issues while using docker (mentioned in discord) was supervisord crashing when the logs directory doesn't exist. supervisord runs X11, X11vnc, and noVNC, so without it, the browser based login doesn't won't work while using docker. The solution was to just create the directory if it doesn't exist in the entrypoint script.
I also added an additional check to wait for the 3 programs to be in a running state before executing the OF-DL binary. The `user=root` line in the supervisord config is simply there to remove a notice that supervisord prints on each execution, and the pidfile configuration simply specifies a different filepath for the supervisord PID file to prevent it from being included in users' volumes.

Fix docker login issue

---

OF DL/Helpers/AuthHelper.cs
docker/supervisord.conf

Addresses https://github.com/sim0n00ps/OF-DL/issues/772
This PR addresses two problems: one relating to docker and one relating to auth.
I added `user=root` to the supervisord config in 1.9.4 to address a warning that supervisord printed in the log (seen below). This change caused issues when users ran the docker container as a different user (using the `-u` docker run parameter). When the docker container user was manually changed, the programs managed by supervisord didn't run, and the OF-DL binary was not executed.
```
2025-04-01 20:24:18,122 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
```
The code change to the AuthHelper …

Fix docker issue when specifying user and auth issue when chromium is closed

---

Dockerfile
OF DL/Program.cs

Solves #687.
Also moved one of the Docker `RUN` commands up to take advantage of caching during `docker build` phase.

Dump config to log file when logging level is changed.
